/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package ec.edu.espol.workshops;

/**
 * @class Library
 * Clase Library
 */
public class Library {
  public boolean someLibraryMethod() {
        return true;
  }
}
